# Book settings
title: Lagrangian Descriptors
author: The CHAMPS Project
logo: champs_logo.jpg

latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url                       : https://github.com/champsproject/lagrangian_descriptors  # Online location of your book
  book_path                 : lagrangian_descriptors  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/champsproject/lagrangian_descriptors/master"  # The URL for your BinderHub